version: "3.8"
services:
  backend:
    container_name: backend-1
    build: ./backend
    ports: 
      - 5000:5000
    volumes:
      - ./backend:/app
    networks:
      - webnet
  frontend:
    build: ./frontend
    ports:
      - 3000:3000
    depends_on:
      - backend
    volumes:
      - ./frontend:/app
    networks:
      - webnet
networks:
  webnet:
